logging:
    level:
        org:
            hibernate:
                SQL: debug
                type:
                    descriptor:
                        sql: trace
            springframework:
                security: DEBUG
spring:
    datasource:
        password: ${{ secrets.AWS_RDS_PASSWORD }}
        url: jdbc:mysql://${{ secrets.AWS_RDS_DATABASE_ADDRESS }}:3306/${{ secrets.AWS_RDS_DATABASE_NAME }}
        username: ${{ secrets.AWS_RDS_USERNAME }}
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
