logging:
    level:
        org:
            hibernate:
                SQL: debug
                type:
                    descriptor:
                        sql: trace
            springframework:
                security: DEBUG
spring:
    datasource:
            driver-class-name: ${{ secrets.AWS_RDS_DATABASE_NAME }}
            url: ${{ secrets.AWS_RDS_DATABASE_ADDRESS_NAME }}
            username: ${{ secrets.AWS_RDS_USERNAME }}
            password: ${{ secrets.AWS_RDS_PASSWORD }}
    jpa:
        generate-ddl: true
        hibernate:
            ddl-auto: none
        properties:
            hibernate:
                format_sql: true
