version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/app/deploy
permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  AfterInstall:
    - location: start.sh
      timeout: 60
      runas: ubuntu