name: Spring Boot & Gradle CI/CD

# Event Trigger
# master branch에 push 또는 pull request가 발생할 경우 동작
# branch 단위 외에도, tag나 cron 식 등을 사용할 수 있음
on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # application.properties 추가정보 입력 시작
      - name: Create ./src/main/resources/
        run: |
          mkdir -p  ./src/main/resources/

      - name: Create ./src/test/resources/
        run: |
          mkdir -p  ./src/test/resources/

      - name: Add Application Property
        run: |
          echo ${{ secrets.RELEASE_APP_PROPERTIES }} > ./src/main/resources/application.properties
          base64 -d -i ./src/main/resources/application.properties > ./src/main/resources/application.properties

      - name: Add Test Application Property
        run: |
          echo ${{ secrets.TEST_APP_PROPERTIES }} > ./src/test/resources/application.properties
          base64 -d -i ./src/test/resources/application.properties > ./src/test/resources/application.properties

      # application.properties 추가정보 입력 끝

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build

      # 배포 폴더 생성 및 압축
      - name: Make Directory for deliver
        run: mkdir -p deploy

      - name: Copy Jar
        run: cp ./build/libs/*.jar ./deploy/

      - name: Make zip file
        run: zip -r -qq -j ./springboot-coup-build.zip ./deploy

      # S3 Bucket으로 전송
      - name: Deliver to AWS S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws s3 cp --region ap-northeast-2 \
          --acl private ./springboot-coup-build.zip ${{ secrets.AWS_S3_BUCKET_ADDRESS }}

      # Deploy
      - name: Deploy
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        run: |
          aws deploy create-deployment \
          --application-name ${{ secrets.AWS_APP_NAME }} \
          --deployment-group-name ${{ secrets.AWS_DEPLOYMENT_GROUP_NAME }} \
          --file-exists-behavior OVERWRITE \
          --s3-location bucket=${{ secrets.AWS_S3_BUCKET_NAME }},bundleType=zip,key=springboot-coup-build.zip \
          --region ap-northeast-2
