name: PR Test

permissions:
  checks: write
  pull-requests: write

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # application.properties 추가정보 입력 시작
      - name: Create ./src/main/resources/
        run: |
          mkdir -p  ./src/main/resources/

      - name: touch Application Property
        run: |
          touch ./src/main/resources/application.properties

      - name: cat application.properties
        run: |
          cat ./src/main/resources/application.properties

      - name: Add Kakao_client_id Application Property
        run: |
          echo ${{ secrets.AUTH_KAKAO_CLIENT_ID }} >> ./src/test/resources/application.properties

      - name: Add Kakao_redirect_uri Application Property
        run: |
          echo ${{ secrets.AUTH_KAKAO_REDIRECT_URI }} >> ./src/test/resources/application.properties

      - name: cat application.properties
        run: |
          cat ./src/main/resources/application.properties
      # application.properties 추가정보 입력 끝

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew --info test

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.33
