name: PR Test

permissions:
  checks: write
  pull-requests: write

on:
  pull_request:
    branches: [ main, dev ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      # application.properties 추가정보 입력 시작
      - name: Create ./src/main/resources/
        run: |
          mkdir -p  ./src/main/resources/

      - name: Create ./src/test/resources/
        run: |
          mkdir -p  ./src/test/resources/

      - name: Add Application Property
        run: |
          echo $RELEASE_APP_PROPERTIES | base64 --decode > ./src/main/resources/application.properties
        env:
          RELEASE_APP_PROPERTIES: ${{ secrets.RELEASE_APP_PROPERTIES }}
      - name: Add Test Application Property
        run: |
          echo $TEST_APP_PROPERTIES | base64 --decode > ./src/test/resources/application.properties
        env:
          TEST_APP_PROPERTIES: ${{ secrets.TEST_APP_PROPERTIES }}

      # application.properties 추가정보 입력 끝

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew --info test

      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v1.33
